language: go

go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/dgryski/go-jump
  - go get github.com/GaryBoone/GoStats/stats
script:
    - $HOME/gopath/bin/goveralls -repotoken 5L09E0PfyiW5MCB6PpC9KCWaILJr1vuoj
